### PR TITLE
fix: Agent code optim

### LINKED ISSUE #849: Add voice feature in chat bar in Nexus app
Request to implement a voice input feature in the chat bar of the Nexus app to enhance user interaction and accessibility.

### LINKED ISSUE #854: Fix handoff issues in Agent and silent text "transfer to..." in model response
There are issues with the handoff process in the Agent where the transition is not smooth. Additionally, the model response includes silent text such as "transfer to..." which should be handled more gracefully or hidden from the user to improve user experience.

### PR DESCRIPTION
**Pull request by FlorentRvl**
This pull request resolves #854 #849                                                                                                        
                                                                                                                                                             
                                    
1. Agent and Tool Enhancements:                                                                                                                             
 - Improved agent name validation and tool binding capabilities.                                                                                             
 - Added default tools and improved tool management in the Agent class.                                                                                      
 - Added a request_help tool for agents to request supervisor assistance.                                                                                    
 - Refactored agent duplication and stream invocation tests.                                                                                                 
                                                                                                                                                             
 2. Intent Handling:                                                                                                                                         
 - Moved default intents to a separate module and integrated them into IntentAgent.                                                                          
                                                                                                                                                             
 3. OpencodeAgent Improvements:                                                                                                                              
 - Updated tool handling and event notifications.                                                                                                            
                                                                                                                                                             
4. ABI Agent Updates:                                                                                                                                       
 - Refined AbiAgent to act as an orchestrator with improved agent and intent management.                                                                     
 - Enhanced system prompt with dynamic tools and agents listing.                                                                                             
                                                                                                                                                             
 5. New Features:                                                                                                                                            
 - Added audio transcription API endpoint using OpenAI.                                                                                                      
 - Added frontend support for voice recording, transcription, and UI components in chat interface.                                                           
                                                                                                                                                             
 6. Ontology and Model Updates:                                                                                                                              
 - Refined RDFEntity base class and related document ontology models for better SPARQL querying and RDF serialization.                                       
                                                                                                                                                             
 7. Dependency Updates:                                                                                                                                      
 - Updated versions of naas-abi and naas-abi-core packages.                                                                                                  
                                                                                                                                                             
 This PR includes significant improvements in agent orchestration, tool management, voice input support, and ontology handling, enhancing the overall system capabilities and user experience.

### CODE REVIEW

File: libs/naas-abi/naas_abi/apps/nexus/apps/web/src/app/api/transcribe/route.ts [hunk 1]
```diff
@@ -0,0 +1,63 @@
+import { NextRequest, NextResponse } from 'next/server';
```
Comment (Dr0p42) [inline libs/naas-abi/naas_abi/apps/nexus/apps/web/src/app/api/transcribe/route.ts:1]: Can we move this to the Python api maybe?

Comment (FlorentRvl) [reply libs/naas-abi/naas_abi/apps/nexus/apps/web/src/app/api/transcribe/route.ts:1]: Yes done !
